import express from 'express';
import crypto from 'crypto';
import pool from '../db/client.js';
import loadConnection from '../lib/loadConnection.js';
import { requireScope } from '../lib/scopes.js';
import { linkedinClient, callLinkedIn } from '../lib/linkedinApi.js';

const router = express.Router();
router.use(loadConnection);

// LinkedIn's SHA256_EMAIL idType expects a lowercase-trimmed email, hashed —
// never the plaintext address itself.
function hashEmail(email) {
  return crypto.createHash('sha256').update(email.trim().toLowerCase()).digest('hex');
}

// GET /conversion-config — the saved default Conversion Rule URN (created in
// LinkedIn Campaign Manager under Analyze > Conversion Tracking; there is no
// API to create one, so it's configured here, not generated by us).
router.get('/conversion-config', async (req, res) => {
  const { rows } = await pool.query(
    'SELECT conversion_rule_urn FROM linkedin_conversion_config WHERE user_id = $1',
    [req.user?.id || 'default_user']
  );
  res.json({ conversion_rule_urn: rows[0]?.conversion_rule_urn || null });
});

// PUT /conversion-config — save/update the default Conversion Rule URN.
router.put('/conversion-config', async (req, res) => {
  const { conversion_rule_urn } = req.body;
  if (!conversion_rule_urn || !conversion_rule_urn.trim()) {
    return res.status(400).json({ error: 'conversion_rule_urn is required' });
  }
  const { rows } = await pool.query(`
    INSERT INTO linkedin_conversion_config (user_id, conversion_rule_urn)
    VALUES ($1, $2)
    ON CONFLICT (user_id) DO UPDATE SET conversion_rule_urn = EXCLUDED.conversion_rule_urn, updated_at = NOW()
    RETURNING conversion_rule_urn
  `, [req.user?.id || 'default_user', conversion_rule_urn.trim()]);
  res.json(rows[0]);
});

// GET /conversions — recent sent events (audit trail).
router.get('/conversions', async (req, res) => {
  const { rows } = await pool.query(
    'SELECT * FROM linkedin_conversion_events WHERE user_id = $1 ORDER BY sent_at DESC LIMIT 50',
    [req.user?.id || 'default_user']
  );
  res.json({ events: rows });
});

// POST /conversions — report an offline/website conversion event to LinkedIn
// so ad performance reflects real outcomes (a lead becoming a customer, a
// deal closing) instead of just clicks. Needs "rw_conversions" (Conversions
// API Product) — approved for this app, so this runs for real, not gated
// behind a partner-access block like org-posting is.
router.post('/conversions', requireScope('rw_conversions'), async (req, res) => {
  const {
    email, first_name, last_name, value, currency, event_id,
    conversion_rule_urn: overrideRule, lead_id,
  } = req.body;

  if (!email || !email.trim()) {
    return res.status(400).json({ error: 'email is required to match the conversion to a LinkedIn ad click' });
  }

  let conversionRuleUrn = overrideRule;
  if (!conversionRuleUrn) {
    const { rows } = await pool.query(
      'SELECT conversion_rule_urn FROM linkedin_conversion_config WHERE user_id = $1',
      [req.user?.id || 'default_user']
    );
    conversionRuleUrn = rows[0]?.conversion_rule_urn;
  }
  if (!conversionRuleUrn) {
    return res.status(400).json({
      error: 'no_conversion_rule_configured',
      message: 'Save a Conversion Rule URN first (Campaign Manager > Analyze > Conversion Tracking), via PUT /conversion-config, or pass conversion_rule_urn on this request.',
    });
  }

  // Deduplication key LinkedIn uses to avoid double-counting the same
  // conversion if this endpoint is ever retried.
  const eventId = event_id || crypto.randomUUID();
  const emailHash = hashEmail(email);
  const valueCents = value != null ? Math.round(Number(value) * 100) : null;
  const currencyCode = currency || 'USD';

  const client = linkedinClient(req.linkedinConnection.access_token);
  const result = await callLinkedIn(() => client.post('/rest/conversionEvents', {
    conversion: conversionRuleUrn,
    conversionHappenedAt: Date.now(),
    eventId,
    ...(valueCents != null ? { conversionValue: { currencyCode, amount: (valueCents / 100).toFixed(2) } } : {}),
    user: {
      userIds: [{ idType: 'SHA256_EMAIL', idValue: emailHash }],
      ...(first_name || last_name ? { userInfo: { firstName: first_name || '', lastName: last_name || '' } } : {}),
    },
  }));

  await pool.query(`
    INSERT INTO linkedin_conversion_events
      (user_id, event_id, conversion_rule_urn, email_hash, value_cents, currency_code, lead_id, status, error_detail)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
    ON CONFLICT (user_id, event_id) DO NOTHING
  `, [
    req.user?.id || 'default_user', eventId, conversionRuleUrn, emailHash,
    valueCents, currencyCode, lead_id || null,
    result.ok ? 'sent' : 'failed', result.ok ? null : JSON.stringify(result.body),
  ]);

  if (!result.ok) {
    return res.status(result.status).json({ error: 'linkedin_conversion_failed', detail: result.body });
  }
  res.status(201).json({ status: 'sent', event_id: eventId });
});

export default router;
