"""Alembic environment.

Runs migrations with a SYNC driver even though the app is async: Alembic's
migration context is synchronous, and mixing asyncpg in here buys nothing.
"""
from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from app.config import get_settings

config = context.config
if config.config_file_name:
    fileConfig(config.config_file_name)


def _sync_url() -> str:
    # asyncpg -> psycopg2 for the migration connection.
    return get_settings().sqlalchemy_url.replace("postgresql+asyncpg://", "postgresql://", 1)


config.set_main_option("sqlalchemy.url", _sync_url())

target_metadata = None  # migrations are hand-written, not autogenerated


def run_migrations_offline() -> None:
    context.configure(
        url=_sync_url(), target_metadata=target_metadata, literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
