/**
 * src/services/graphApi.js
 *
 * Shared helpers for calling Meta's Graph API safely and consistently:
 *   - central place for the base URL + version (see also .env: META_GRAPH_API_BASE, META_GRAPH_API_VERSION)
 *   - appsecret_proof generation, required on every authenticated call
 *
 * Docs: https://developers.facebook.com/docs/graph-api/securing-requests
 */

const crypto = require('crypto');

const GRAPH_BASE = process.env.META_GRAPH_API_BASE || 'https://graph.facebook.com';
const GRAPH_VERSION = process.env.META_GRAPH_API_VERSION || 'v25.0';
const GRAPH_URL = `${GRAPH_BASE}/${GRAPH_VERSION}`;

/**
 * Computes appsecret_proof: an HMAC-SHA256 hash of the access token,
 * signed with the App Secret. Meta uses this to verify a Graph API call
 * genuinely originates from a server that holds the App Secret — it
 * protects against a leaked/stolen access token being used elsewhere,
 * since the proof can only be generated by someone who also has the secret.
 */
function getAppSecretProof(accessToken) {
  return crypto
    .createHmac('sha256', process.env.META_APP_SECRET)
    .update(accessToken)
    .digest('hex');
}

/**
 * Appends access_token + appsecret_proof to a params object/URLSearchParams
 * and returns a URLSearchParams ready to use in a fetch call.
 */
function withAuth(params, accessToken) {
  const merged = new URLSearchParams(params);
  merged.set('access_token', accessToken);
  merged.set('appsecret_proof', getAppSecretProof(accessToken));
  return merged;
}

/**
 * Validates a token using Meta's /debug_token endpoint. Confirms the token
 * is still valid (not expired/revoked), and returns useful metadata —
 * expiry, granted scopes, and which app/user it belongs to.
 *
 * Requires an "app access token" (client_id|client_secret combo) to
 * authorize the debug call itself — this is standard practice and does
 * not require a separate OAuth flow to obtain.
 *
 * Docs: https://developers.facebook.com/docs/graph-api/reference/debug_token
 *
 * Returns: { valid: boolean, expiresAt: Date|null, scopes: string[], raw: object }
 */
async function validateToken(tokenToCheck) {
  const appAccessToken = `${process.env.META_APP_ID}|${process.env.META_APP_SECRET}`;

  const res = await fetch(
    `${GRAPH_URL}/debug_token?` +
      new URLSearchParams({
        input_token: tokenToCheck,
        access_token: appAccessToken,
      })
  );
  const data = await res.json();

  if (data.error) {
    console.error('Token validation request failed:', data.error);
    return { valid: false, expiresAt: null, scopes: [], raw: data };
  }

  const info = data.data || {};
  const expiresAt = info.expires_at ? new Date(info.expires_at * 1000) : null;

  return {
    valid: Boolean(info.is_valid),
    expiresAt,
    scopes: info.scopes || [],
    raw: info,
  };
}

/**
 * Parses and verifies a Meta "signed_request" — the format used for
 * Deauthorize and Data Deletion callbacks. It's a base64url-encoded
 * signature + base64url-encoded JSON payload, joined by a dot, HMAC-SHA256
 * signed with the App Secret. We must verify the signature before trusting
 * any of the payload's contents (e.g. user_id).
 *
 * Docs: https://developers.facebook.com/docs/facebook-login/guides/advanced/existing-token#appsecret_proof
 *       https://developers.facebook.com/docs/development/create-an-app/app-dashboard/data-deletion-callback
 *
 * Returns the decoded payload object if valid, or null if the signature
 * doesn't match (payload should not be trusted / request should be rejected).
 */
function base64UrlDecode(input) {
  const padded = input.replace(/-/g, '+').replace(/_/g, '/');
  const pad = padded.length % 4 === 0 ? '' : '='.repeat(4 - (padded.length % 4));
  return Buffer.from(padded + pad, 'base64');
}

function parseSignedRequest(signedRequest) {
  const [encodedSig, encodedPayload] = (signedRequest || '').split('.');
  if (!encodedSig || !encodedPayload) return null;

  const expectedSig = crypto
    .createHmac('sha256', process.env.META_APP_SECRET)
    .update(encodedPayload)
    .digest();

  const actualSig = base64UrlDecode(encodedSig);

  if (
    actualSig.length !== expectedSig.length ||
    !crypto.timingSafeEqual(actualSig, expectedSig)
  ) {
    return null;
  }

  try {
    return JSON.parse(base64UrlDecode(encodedPayload).toString('utf8'));
  } catch {
    return null;
  }
}

module.exports = { GRAPH_URL, GRAPH_VERSION, GRAPH_BASE, getAppSecretProof, withAuth, validateToken, parseSignedRequest };