'use client';
import { useState } from 'react';
import { Sparkles, Copy, RefreshCw, ChevronDown, FileText, MessageSquare, Mail, Megaphone, Hash, Save } from 'lucide-react';
import { useMHToast } from '../ui/MHToast';
import { useContentList, useGenerateContent, useCreateContent } from '@/lib/queries/marketingHub';

const TABS = [
  { id: 'social', label: 'Social Post', icon: Hash, channel: 'social', llmType: 'post' },
  { id: 'email', label: 'Email', icon: Mail, channel: 'email', llmType: 'campaign' },
  { id: 'ad', label: 'Ad Copy', icon: Megaphone, channel: 'social', llmType: 'post' },
  { id: 'blog', label: 'Blog Outline', icon: FileText, channel: 'email', llmType: 'post' },
  { id: 'whatsapp', label: 'WhatsApp', icon: MessageSquare, channel: 'whatsapp', llmType: 'campaign' },
];

const CAMPAIGN_TYPES = ['Lead Generation', 'Brand Awareness', 'Product Launch', 'Event Promotion', 'Retargeting', 'Webinar'];
const INDUSTRIES = ['EdTech', 'SaaS', 'E-commerce', 'Healthcare', 'Finance', 'Real Estate'];
const GOALS = ['Drive Sign-ups', 'Generate Leads', 'Increase Awareness', 'Boost Sales', 'Event Registrations', 'App Downloads'];

function buildPrompt({ tab, campaignType, industry, goal, details }) {
  const base = `Write a ${tab.label.toLowerCase()} for a ${industry} business running a "${campaignType}" campaign. Goal: ${goal}.`;
  return details.trim() ? `${base} Additional context: ${details.trim()}` : base;
}

export default function MHContentStudio() {
  const toast = useMHToast();
  const [activeTab, setActiveTab] = useState('social');
  const [campaignType, setCampaignType] = useState('Lead Generation');
  const [industry, setIndustry] = useState('EdTech');
  const [goal, setGoal] = useState('Drive Sign-ups');
  const [details, setDetails] = useState('');
  const [generated, setGenerated] = useState(null);
  const [usedFallback, setUsedFallback] = useState(false);
  const [saved, setSaved] = useState(false);

  const generateContent = useGenerateContent();
  const createContent = useCreateContent();
  const { data: recent = [] } = useContentList({ limit: 5 });

  const tab = TABS.find((t) => t.id === activeTab);

  const handleGenerate = async () => {
    setSaved(false);
    try {
      const result = await generateContent.mutateAsync({
        prompt: buildPrompt({ tab, campaignType, industry, goal, details }),
        type: tab.llmType,
        channel: tab.channel,
        tone: 'friendly',
        length: activeTab === 'blog' ? 'long' : 'medium',
      });
      setGenerated(result.content);
      setUsedFallback(!!result.metadata?.usedFallback);
      toast.show(result.metadata?.usedFallback ? 'Generated (LLM unavailable — used a template fallback)' : 'Content generated by AI!', result.metadata?.usedFallback ? 'info' : 'success');
    } catch (err) {
      toast.show(err.message || 'Generation failed', 'error');
    }
  };

  const handleCopy = () => {
    navigator.clipboard?.writeText(generated || '');
    toast.show('Copied to clipboard!', 'success');
  };

  const handleSave = async () => {
    if (!generated) return;
    try {
      await createContent.mutateAsync({
        name: `${campaignType} — ${tab.label}`,
        type: tab.llmType,
        channel: tab.channel,
        content: generated,
        tags: [industry, goal],
      });
      setSaved(true);
      toast.show('Saved to your content library', 'success');
    } catch (err) {
      toast.show(err.message || 'Save failed', 'error');
    }
  };

  return (
    <div style={{ padding: '24px 28px', background: 'var(--mh-bg)', minHeight: '100vh' }}>
      {/* Header */}
      <div style={{ marginBottom: 24 }}>
        <h1 style={{ fontFamily: 'var(--mh-font-display)', fontSize: 22, fontWeight: 700, color: 'var(--mh-text)', margin: 0 }}>Content Studio</h1>
        <p style={{ fontSize: 13, color: 'var(--mh-text-3)', marginTop: 4 }}>Generate high-converting marketing content with a real LLM call</p>
      </div>

      {/* Tab Bar */}
      <div style={{ display: 'flex', borderBottom: '1px solid var(--mh-border)', marginBottom: 24, gap: 0, background: '#fff', borderRadius: '14px 14px 0 0', padding: '0 4px', boxShadow: 'var(--mh-shadow-sm)' }}>
        {TABS.map((t) => {
          const Icon = t.icon;
          return (
            <button key={t.id} onClick={() => { setActiveTab(t.id); setGenerated(null); setSaved(false); }}
              style={{ padding: '12px 18px', fontSize: 13, background: 'none', border: 'none', cursor: 'pointer', borderBottom: `2px solid ${activeTab === t.id ? '#6366f1' : 'transparent'}`, color: activeTab === t.id ? '#6366f1' : '#6b7280', fontWeight: activeTab === t.id ? 600 : 400, display: 'flex', alignItems: 'center', gap: 6, transition: 'all 0.15s', whiteSpace: 'nowrap' }}>
              <Icon size={14} />{t.label}
            </button>
          );
        })}
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20, alignItems: 'start' }}>
        {/* Left: Form */}
        <div style={{ background: '#fff', border: '1px solid var(--mh-border)', borderRadius: 14, padding: '24px', boxShadow: 'var(--mh-shadow-sm)' }}>
          <div style={{ fontFamily: 'var(--mh-font-display)', fontSize: 15, fontWeight: 700, color: '#111827', marginBottom: 20 }}>Content Settings</div>

          <div style={{ marginBottom: 16 }}>
            <label style={{ fontSize: 11, fontWeight: 600, letterSpacing: '0.06em', textTransform: 'uppercase', color: '#6b7280', display: 'block', marginBottom: 6 }}>Campaign Type</label>
            <div style={{ position: 'relative' }}>
              <select className="mh-input" value={campaignType} onChange={(e) => setCampaignType(e.target.value)} style={{ width: '100%', appearance: 'none', paddingRight: 28 }}>
                {CAMPAIGN_TYPES.map((c) => <option key={c}>{c}</option>)}
              </select>
              <ChevronDown size={13} style={{ position: 'absolute', right: 10, top: '50%', transform: 'translateY(-50%)', pointerEvents: 'none', color: '#9ca3af' }} />
            </div>
          </div>

          <div style={{ marginBottom: 16 }}>
            <label style={{ fontSize: 11, fontWeight: 600, letterSpacing: '0.06em', textTransform: 'uppercase', color: '#6b7280', display: 'block', marginBottom: 6 }}>Industry</label>
            <div style={{ position: 'relative' }}>
              <select className="mh-input" value={industry} onChange={(e) => setIndustry(e.target.value)} style={{ width: '100%', appearance: 'none', paddingRight: 28 }}>
                {INDUSTRIES.map((i) => <option key={i}>{i}</option>)}
              </select>
              <ChevronDown size={13} style={{ position: 'absolute', right: 10, top: '50%', transform: 'translateY(-50%)', pointerEvents: 'none', color: '#9ca3af' }} />
            </div>
          </div>

          <div style={{ marginBottom: 16 }}>
            <label style={{ fontSize: 11, fontWeight: 600, letterSpacing: '0.06em', textTransform: 'uppercase', color: '#6b7280', display: 'block', marginBottom: 6 }}>Goal</label>
            <div style={{ position: 'relative' }}>
              <select className="mh-input" value={goal} onChange={(e) => setGoal(e.target.value)} style={{ width: '100%', appearance: 'none', paddingRight: 28 }}>
                {GOALS.map((g) => <option key={g}>{g}</option>)}
              </select>
              <ChevronDown size={13} style={{ position: 'absolute', right: 10, top: '50%', transform: 'translateY(-50%)', pointerEvents: 'none', color: '#9ca3af' }} />
            </div>
          </div>

          <div style={{ marginBottom: 20 }}>
            <label style={{ fontSize: 11, fontWeight: 600, letterSpacing: '0.06em', textTransform: 'uppercase', color: '#6b7280', display: 'block', marginBottom: 6 }}>Extra Details</label>
            <textarea className="mh-input" value={details} onChange={(e) => setDetails(e.target.value)}
              placeholder="Describe your product, target audience, tone, or any specific requirements…"
              style={{ width: '100%', minHeight: 100, resize: 'vertical', lineHeight: 1.6 }} />
          </div>

          <button className="mh-btn mh-btn-ai" onClick={handleGenerate} disabled={generateContent.isPending}
            style={{ width: '100%', justifyContent: 'center', fontSize: 14, padding: '11px 20px', opacity: generateContent.isPending ? 0.8 : 1 }}>
            {generateContent.isPending ? <><RefreshCw size={15} className="mh-animate-spin" /> Generating…</> : <><Sparkles size={15} /> Generate with AI</>}
          </button>
        </div>

        {/* Right: Preview */}
        <div>
          <div style={{ background: '#fff', border: '1px solid var(--mh-border)', borderRadius: 14, padding: '24px', boxShadow: 'var(--mh-shadow-sm)', minHeight: 320 }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>
              <div style={{ fontFamily: 'var(--mh-font-display)', fontSize: 15, fontWeight: 700, color: '#111827' }}>Generated Content</div>
              {generated && (
                <div style={{ display: 'flex', gap: 8 }}>
                  <button className="mh-btn mh-btn-ghost" style={{ fontSize: 12 }} onClick={handleCopy}><Copy size={13} /> Copy</button>
                  <button className="mh-btn mh-btn-ghost" style={{ fontSize: 12 }} onClick={handleGenerate}><RefreshCw size={13} /> Regenerate</button>
                  <button className="mh-btn mh-btn-primary" style={{ fontSize: 12 }} onClick={handleSave} disabled={saved || createContent.isPending}>
                    <Save size={13} /> {saved ? 'Saved' : 'Save'}
                  </button>
                </div>
              )}
            </div>
            {usedFallback && generated && (
              <div style={{ fontSize: 11, color: '#d97706', background: '#fffbeb', border: '1px solid #fde68a', borderRadius: 8, padding: '6px 10px', marginBottom: 12 }}>
                The LLM call failed, so this is a template fallback, not a real AI generation.
              </div>
            )}
            {!generated && !generateContent.isPending && (
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', minHeight: 220, color: '#9ca3af', gap: 12 }}>
                <Sparkles size={36} style={{ color: '#e5e7eb' }} />
                <div style={{ fontSize: 13 }}>Fill in the settings and click Generate with AI</div>
              </div>
            )}
            {generateContent.isPending && (
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', minHeight: 220, gap: 12 }}>
                <div className="mh-skeleton" style={{ width: '100%', height: 16, marginBottom: 6 }} />
                <div className="mh-skeleton" style={{ width: '90%', height: 16, marginBottom: 6 }} />
                <div className="mh-skeleton" style={{ width: '80%', height: 16, marginBottom: 6 }} />
                <div className="mh-skeleton" style={{ width: '85%', height: 16, marginBottom: 6 }} />
                <div style={{ fontSize: 12, color: '#9ca3af', marginTop: 8 }}>AI is crafting your content…</div>
              </div>
            )}
            {generated && !generateContent.isPending && (
              <pre style={{ fontFamily: 'var(--mh-font-body)', fontSize: 13, color: '#374151', whiteSpace: 'pre-wrap', lineHeight: 1.7, margin: 0, background: '#f9fafb', borderRadius: 10, padding: 16, border: '1px solid #f3f4f6', maxHeight: 400, overflow: 'auto' }}>{generated}</pre>
            )}
          </div>
        </div>
      </div>

      {/* Recent Generations — real saved content, not static sample rows */}
      <div style={{ marginTop: 24, background: '#fff', border: '1px solid var(--mh-border)', borderRadius: 14, boxShadow: 'var(--mh-shadow-sm)', overflow: 'hidden' }}>
        <div style={{ padding: '16px 20px', borderBottom: '1px solid #f3f4f6' }}>
          <div style={{ fontFamily: 'var(--mh-font-display)', fontSize: 15, fontWeight: 700, color: '#111827' }}>Recent Generations</div>
        </div>
        {recent.length === 0 ? (
          <div style={{ padding: '32px 20px', textAlign: 'center', fontSize: 13, color: '#9ca3af' }}>Nothing saved yet — generate something above and hit Save.</div>
        ) : (
          <div style={{ padding: '8px 0' }}>
            {recent.map((r) => (
              <div key={r.id} style={{ display: 'flex', alignItems: 'center', gap: 16, padding: '12px 20px', borderBottom: '1px solid #f9fafb' }}>
                <div style={{ width: 36, height: 36, borderRadius: 8, background: '#eef2ff', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <FileText size={16} style={{ color: '#6366f1' }} />
                </div>
                <div style={{ flex: 1 }}>
                  <div style={{ fontSize: 13, fontWeight: 600, color: '#111827' }}>{r.name}</div>
                  <div style={{ fontSize: 11, color: '#9ca3af', marginTop: 2 }}>{r.channel} · {new Date(r.created_at).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })}</div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
